"use client";

import { useEffect, useState } from "react";
import { authClient } from "@/lib/auth-client";

type ParsedQuestion = { id:number; subject:string; question:string; options:string[]; answer:string; explanation:string; pageNumber?:number; hasImage?:boolean; imagePreviewUrl?:string };
type Visibility="public"|"private";
type QuestionSet={id:number;name:string;filename:string|null;total_questions:number;created_at:string;file_hash:string|null;visibility:Visibility;owner_id:string|null;exam_subject:string|null;exam_year:number|null};
type ManualQuestion={question:string;options:string[];answer:string;explanation:string};
const EXAM_SUBJECTS=["獸醫病理學","獸醫藥理學","獸醫實驗診斷學","獸醫普通疾病學","獸醫傳染病學","獸醫公共衛生學"];
const EXAM_YEARS=Array.from({length:10},(_,index)=>new Date().getFullYear()-1911-index);

export default function PDFPage(){
 const {data:session,isPending:sessionLoading,refetch:refetchSession}=authClient.useSession();
 const [subscription,setSubscription]=useState<{plan:string;status:string}|null>(null),[subscriptionLoading,setSubscriptionLoading]=useState(true),[isAdmin,setIsAdmin]=useState(false),[adminLoading,setAdminLoading]=useState(true),[file,setFile]=useState<File|null>(null),[questions,setQuestions]=useState<ParsedQuestion[]>([]),[importMode,setImportMode]=useState<"pdf"|"manual">("pdf"),[manualSetName,setManualSetName]=useState(""),[manualQuestions,setManualQuestions]=useState<ManualQuestion[]>([{question:"",options:["","","",""],answer:"",explanation:""}]),[manualLoading,setManualLoading]=useState(false),[manualMessage,setManualMessage]=useState(""),[questionSets,setQuestionSets]=useState<QuestionSet[]>([]),[currentQuestionSetId,setCurrentQuestionSetId]=useState<number|null>(null),[deletingQuestionSetId,setDeletingQuestionSetId]=useState<number|null>(null),[examSubject,setExamSubject]=useState(""),[examYear,setExamYear]=useState<number|"">(""),[visibility,setVisibility]=useState<Visibility>("private"),[loading,setLoading]=useState(false),[loadingQuestionSets,setLoadingQuestionSets]=useState(true),[message,setMessage]=useState(""),[upgradeRequired,setUpgradeRequired]=useState(false);
 const isLoggedIn=!!session?.user,isPro=subscription?.plan==="pro"&&subscription?.status==="active";
 useEffect(()=>{if(!sessionLoading){loadQuestionSets();loadSubscription();loadAdminStatus()}},[sessionLoading,session?.user?.id]);
 async function loadAdminStatus(){if(!session?.user?.id){setIsAdmin(false);setAdminLoading(false);return}try{setAdminLoading(true);const r=await fetch("/api/admin/status",{cache:"no-store"}),d=await r.json();if(!r.ok){setIsAdmin(false);return}setIsAdmin(d.isAdmin===true);if(d.isAdmin!==true)setVisibility("private")}catch(e){console.error(e);setIsAdmin(false);setVisibility("private")}finally{setAdminLoading(false)}}
 async function loadSubscription(){if(!session?.user?.id){setSubscription(null);setSubscriptionLoading(false);return}try{setSubscriptionLoading(true);const r=await fetch("/api/subscription",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.detail||d.error);setSubscription(d.subscription||null)}catch(e){console.error(e);setSubscription(null)}finally{setSubscriptionLoading(false)}}
 async function loadQuestionSets(){try{setLoadingQuestionSets(true);const r=await fetch("/api/question-sets",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.detail||d.error);setQuestionSets(d.questionSets||[])}catch(e){console.error(e)}finally{setLoadingQuestionSets(false)}}
 async function deleteSavedQuestionSet(q:QuestionSet){if(!isLoggedIn)return;if(!window.confirm(`確定要刪除「${q.name}」嗎？\n\n這會永久刪除這個題庫以及其中所有題目，無法復原。`))return;try{setDeletingQuestionSetId(q.id);const r=await fetch("/api/question-sets",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionSetId:q.id})}),d=await r.json();if(!r.ok)throw new Error(d.detail||d.error);setQuestionSets(c=>c.filter(x=>x.id!==q.id));if(currentQuestionSetId===q.id){setCurrentQuestionSetId(null);setQuestions([])}setMessage(`已刪除題庫「${q.name}」。`)}catch(e){setMessage(e instanceof Error?`刪除失敗：${e.message}`:"刪除題庫失敗。")}finally{setDeletingQuestionSetId(null)}}
 async function handleLogout(){try{await authClient.signOut();await refetchSession();setSubscription(null);setIsAdmin(false);location.href="/"}catch(e){console.error(e)}}
 function handleFileChange(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]||null;setQuestions([]);setCurrentQuestionSetId(null);setMessage("");setUpgradeRequired(false);if(!f){setFile(null);return}if(f.type!=="application/pdf"){setFile(null);setMessage("請選擇 PDF 檔案");return}if(f.size>20*1024*1024){setFile(null);setMessage("PDF 檔案不能超過 20 MB");return}setFile(f);setMessage(`已選擇 PDF：${f.name}`)}
 async function handleUpload(){setUpgradeRequired(false);if(!isLoggedIn){setMessage("請先登入後再使用 PDF 匯入功能。");return}if(!file){setMessage("請先選擇 PDF 檔案");return}setLoading(true);setMessage("正在解析 PDF，請稍候...");setQuestions([]);setCurrentQuestionSetId(null);try{const fd=new FormData();fd.append("file",file);fd.append("visibility",visibility);if(examSubject)fd.append("exam_subject",examSubject);if(examYear)fd.append("examYear",String(Number(examYear)+1911));const r=await fetch("/api/pdf",{method:"POST",body:fd}),t=await r.text();let d:any;try{d=JSON.parse(t)}catch{throw new Error(`伺服器沒有正常回傳 JSON（HTTP ${r.status}）。`)}if(!r.ok){if(r.status===403&&d.code==="ADMIN_REQUIRED"){setMessage("只有管理員可以建立公開國考題庫。");return}if(r.status===403||d.code==="PRO_REQUIRED"){setUpgradeRequired(true);setMessage("此功能需要 PRO 會員才能使用。");return}if(r.status===401){setMessage("請先登入後再使用 PDF 匯入功能。");return}throw new Error(d.detail||d.error||`PDF 解析失敗（HTTP ${r.status}）`)}const parsed=d.questions||[];if(!parsed.length){setMessage("PDF 有成功送到伺服器，但沒有辨識到題目。");return}setQuestions(parsed);setMessage(`成功辨識 ${parsed.length} 題。請先檢查題目、選項與圖片，再確認匯入。`)}catch(e){console.error(e);setMessage(e instanceof Error?e.message:"PDF 解析失敗。")}finally{setLoading(false)}}
 function updateQuestion(id:number,value:string){setQuestions(c=>c.map(q=>q.id===id?{...q,question:value}:q))}function updateOption(id:number,i:number,value:string){setQuestions(c=>c.map(q=>q.id===id?{...q,options:q.options.map((o,j)=>j===i?value:o)}:q))}function deleteQuestion(id:number){setQuestions(c=>c.filter(q=>q.id!==id))}
 function startQuiz(){if(!questions.length){setMessage("目前沒有可以開始的題目。");return}setMessage("目前解析結果已確認。正式資料庫匯入流程將在確認按鈕接上後執行。");}
 function addManualQuestion(){setManualQuestions(c=>[...c,{question:"",options:["","","",""],answer:"",explanation:""}])}function removeManualQuestion(i:number){setManualQuestions(c=>c.filter((_,j)=>j!==i))}function updateManualQuestion(i:number,v:string){setManualQuestions(c=>c.map((q,j)=>j===i?{...q,question:v}:q))}function updateManualOption(i:number,j:number,v:string){setManualQuestions(c=>c.map((q,k)=>k===i?{...q,options:q.options.map((o,x)=>x===j?v:o)}:q))}function updateManualAnswer(i:number,v:string){setManualQuestions(c=>c.map((q,j)=>j===i?{...q,answer:v}:q))}function updateManualExplanation(i:number,v:string){setManualQuestions(c=>c.map((q,j)=>j===i?{...q,explanation:v}:q))}
 return <main className="min-h-screen bg-gray-100 p-6 md:p-10"><div className="mx-auto max-w-6xl"><div className="mb-8 flex items-center justify-between"><div><h1 className="text-4xl font-bold">PDF 題庫匯入</h1><p className="mt-2 text-gray-500">先解析與確認，確認後再匯入題庫</p></div>{isLoggedIn&&<button onClick={handleLogout} className="rounded-lg border bg-white px-4 py-2">登出</button>}</div>
  <section className="rounded-2xl bg-white p-6 shadow"><div className="grid gap-4 md:grid-cols-2"><label className="rounded-xl border p-4"><span className="font-bold">PDF 檔案</span><input className="mt-3 block w-full" type="file" accept="application/pdf" onChange={handleFileChange}/>{file&&<p className="mt-2 text-sm text-gray-500">{file.name}</p>}</label><div><label className="block font-bold">國考科目</label><select value={examSubject} onChange={e=>setExamSubject(e.target.value)} className="mt-2 w-full rounded-lg border p-3"><option value="">請選擇科目</option>{EXAM_SUBJECTS.map(s=><option key={s}>{s}</option>)}</select>{examSubject&&<><label className="mt-4 block font-bold">國考年份</label><select value={examYear} onChange={e=>setExamYear(e.target.value?Number(e.target.value):"")} className="mt-2 w-full rounded-lg border p-3"><option value="">不指定年份</option>{EXAM_YEARS.map(y=><option key={y} value={y}>民國 {y} 年</option>)}</select></>}</div></div><button onClick={handleUpload} disabled={loading||!file||!isLoggedIn||!isPro} className="mt-6 rounded-lg bg-blue-600 px-6 py-3 font-bold text-white disabled:bg-gray-400">{loading?"解析中...":"開始解析 PDF"}</button>{message&&<div className="mt-4 rounded-lg bg-gray-50 p-4">{message}</div>}</section>
  {questions.length>0&&<section className="mt-8"><div className="mb-5 rounded-2xl bg-white p-6 shadow"><div className="flex items-center justify-between gap-4"><div><h2 className="text-2xl font-bold">② 檢查解析結果</h2><p className="mt-2 text-gray-600">共 {questions.length} 題。請確認文字、選項與圖片。</p></div><button onClick={startQuiz} className="rounded-lg bg-green-600 px-6 py-3 font-bold text-white">確認匯入</button></div></div><div className="space-y-6">{questions.map((q,i)=><article key={`${q.id}-${i}`} className="rounded-2xl bg-white p-6 shadow"><div className="flex items-center justify-between"><b className="text-blue-600">第 {i+1} 題</b>{q.hasImage&&<span className="rounded-full bg-amber-50 px-3 py-1 text-sm font-semibold text-amber-700">🖼 此題包含圖片 · PDF 第 {q.pageNumber} 頁</span>}<button onClick={()=>deleteQuestion(q.id)} className="text-red-600">刪除</button></div><textarea value={q.question} onChange={e=>updateQuestion(q.id,e.target.value)} rows={4} className="mt-4 w-full rounded-lg border p-4 text-lg font-semibold"/>{q.hasImage&&<div className="mt-4 rounded-xl border-2 border-dashed border-amber-200 bg-amber-50 p-4"><p className="font-bold text-amber-800">圖片預覽</p><p className="mt-1 text-sm text-amber-700">這題的圖片位於原 PDF 第 {q.pageNumber} 頁。目前 API 已能辨識圖片頁；下一步將把原始 PDF 頁面轉成實際圖片預覽。</p></div>}<div className="mt-5 space-y-3">{q.options.map((o,j)=><div key={j} className="flex gap-3"><b className="mt-3 w-8">{String.fromCharCode(65+j)}</b><textarea value={o} onChange={e=>updateOption(q.id,j,e.target.value)} rows={2} className="w-full rounded-lg border p-3"/></div>)}</div></article>)}</div></section>}
 </div></main>
}
