"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { authClient } from "@/lib/auth-client";
import ImagePreview from "./ImagePreview";

type ParsedQuestion = { id:number; subject:string; question:string; options:string[]; answer:string; explanation:string; pageNumber?:number; hasImage?:boolean };
type Visibility="public"|"private";
type QuestionSet={id:number;name:string;filename:string|null;total_questions:number;created_at:string;file_hash:string|null;visibility:Visibility;owner_id:string|null;exam_subject:string|null;exam_year:number|null};
const EXAM_SUBJECTS=["獸醫病理學","獸醫藥理學","獸醫實驗診斷學","獸醫普通疾病學","獸醫傳染病學","獸醫公共衛生學"];
const EXAM_YEARS=Array.from({length:10},(_,i)=>new Date().getFullYear()-1911-i);

export default function PDFPage(){
 const {data:session,isPending:sessionLoading,refetch:refetchSession}=authClient.useSession();
 const [subscription,setSubscription]=useState<{plan:string;status:string}|null>(null),[isAdmin,setIsAdmin]=useState(false),[file,setFile]=useState<File|null>(null),[questions,setQuestions]=useState<ParsedQuestion[]>([]),[questionSets,setQuestionSets]=useState<QuestionSet[]>([]),[currentQuestionSetId,setCurrentQuestionSetId]=useState<number|null>(null),[deletingQuestionSetId,setDeletingQuestionSetId]=useState<number|null>(null),[examSubject,setExamSubject]=useState(""),[examYear,setExamYear]=useState<number|"">(""),[visibility,setVisibility]=useState<Visibility>("private"),[loading,setLoading]=useState(false),[loadingQuestionSets,setLoadingQuestionSets]=useState(true),[message,setMessage]=useState(""),[fileHash,setFileHash]=useState("");
 const isLoggedIn=!!session?.user,isPro=subscription?.plan==="pro"&&subscription?.status==="active";
 useEffect(()=>{if(!sessionLoading){loadQuestionSets();loadSubscription();loadAdminStatus()}},[sessionLoading,session?.user?.id]);
 async function loadAdminStatus(){if(!session?.user?.id){setIsAdmin(false);return}try{const r=await fetch("/api/admin/status",{cache:"no-store"}),d=await r.json();setIsAdmin(r.ok&&d.isAdmin===true);if(!d.isAdmin)setVisibility("private")}catch{setIsAdmin(false);setVisibility("private")}}
 async function loadSubscription(){if(!session?.user?.id){setSubscription(null);return}try{const r=await fetch("/api/subscription",{cache:"no-store"}),d=await r.json();setSubscription(r.ok?d.subscription||null:null)}catch{setSubscription(null)}}
 async function loadQuestionSets(){try{setLoadingQuestionSets(true);const r=await fetch("/api/question-sets",{cache:"no-store"}),d=await r.json();if(r.ok)setQuestionSets(d.questionSets||[])}catch(e){console.error(e)}finally{setLoadingQuestionSets(false)}}
 async function deleteSavedQuestionSet(q:QuestionSet){if(!isLoggedIn)return;if(!window.confirm(`確定要刪除「${q.name}」嗎？\n\n這會永久刪除這個題庫以及其中所有題目，無法復原。`))return;try{setDeletingQuestionSetId(q.id);const r=await fetch("/api/question-sets",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionSetId:q.id})}),d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||"刪除失敗");setQuestionSets(c=>c.filter(x=>x.id!==q.id));if(currentQuestionSetId===q.id){setCurrentQuestionSetId(null);setQuestions([])}setMessage(`已刪除題庫「${q.name}」。`)}catch(e){setMessage(e instanceof Error?`刪除失敗：${e.message}`:"刪除題庫失敗。")}finally{setDeletingQuestionSetId(null)}}
 async function handleLogout(){try{await authClient.signOut();await refetchSession();location.href="/"}catch(e){console.error(e)}}
 function handleFileChange(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]||null;setQuestions([]);setCurrentQuestionSetId(null);setFileHash("");setMessage("");if(!f){setFile(null);return}if(f.type!=="application/pdf"){setFile(null);setMessage("請選擇 PDF 檔案");return}if(f.size>20*1024*1024){setFile(null);setMessage("PDF 檔案不能超過 20 MB");return}setFile(f);setMessage(`已選擇 PDF：${f.name}`)}
 async function handleUpload(){if(!isLoggedIn){setMessage("請先登入後再使用 PDF 匯入功能。");return}if(!isPro){setMessage("此功能需要 PRO 會員才能使用。");return}if(!file){setMessage("請先選擇 PDF 檔案");return}if(!examSubject){setMessage("請選擇國考科目。");return}setLoading(true);setMessage("正在解析 PDF，請稍候...");setQuestions([]);setCurrentQuestionSetId(null);setFileHash("");try{const fd=new FormData();fd.append("file",file);fd.append("visibility",visibility);fd.append("exam_subject",examSubject);if(examYear)fd.append("examYear",String(Number(examYear)+1911));const r=await fetch("/api/pdf",{method:"POST",body:fd}),t=await r.text();let d:any;try{d=JSON.parse(t)}catch{throw new Error(`伺服器沒有正常回傳 JSON（HTTP ${r.status}）。`)}if(!r.ok)throw new Error(d.detail||d.error||`PDF 解析失敗（HTTP ${r.status}）`);const parsed=d.questions||[];if(!parsed.length){setMessage("PDF 有成功送到伺服器，但沒有辨識到題目。");return}setQuestions(parsed);setFileHash(typeof d.fileHash==="string"?d.fileHash:"");setMessage(`成功辨識 ${parsed.length} 題。請先檢查題目、選項與圖片，再確認匯入。`)}catch(e){console.error(e);setMessage(e instanceof Error?e.message:"PDF 解析失敗。")}finally{setLoading(false)}}
 function updateQuestion(id:number,value:string){setQuestions(c=>c.map(q=>q.id===id?{...q,question:value}:q))}function updateOption(id:number,i:number,value:string){setQuestions(c=>c.map(q=>q.id===id?{...q,options:q.options.map((o,j)=>j===i?value:o)}:q))}function deleteQuestion(id:number){setQuestions(c=>c.filter(q=>q.id!==id))}
 async function confirmImport(){if(!questions.length){setMessage("目前沒有可以確認的題目。");return}if(!isLoggedIn){setMessage("請先登入後再匯入題庫。");return}if(!fileHash){setMessage("找不到這份 PDF 的檔案指紋，請重新解析 PDF 後再確認匯入。");return}setLoading(true);setMessage("正在正式匯入資料庫，請稍候...");try{const r=await fetch("/api/question-sets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questions,filename:file?.name||"PDF 題庫.pdf",fileHash,visibility,examSubject,examYear:examYear?Number(examYear)+1911:new Date().getFullYear()})});const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||"匯入題庫失敗");setCurrentQuestionSetId(Number(d.questionSetId));setMessage(`✅ ${d.message||`已確認匯入 ${questions.length} 題。`}`);setQuestions([]);setFile(null);setFileHash("");await loadQuestionSets()}catch(e){console.error(e);setMessage(e instanceof Error?e.message:"匯入題庫失敗。")}finally{setLoading(false)}}
 return <main className="min-h-screen bg-gradient-to-b from-slate-50 via-white to-slate-100 px-4 py-8 md:px-8 md:py-10"><div className="mx-auto max-w-6xl">
  <div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 inline-flex items-center rounded-full border border-blue-100 bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">VetExam · 題庫管理</div><h1 className="text-3xl font-bold tracking-tight text-slate-900 md:text-4xl">PDF 題庫匯入</h1><p className="mt-2 text-slate-500">先解析、檢查題目與圖片，確認後再匯入題庫</p></div>{isLoggedIn&&<div className="flex items-center gap-2"><Link href="/" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 shadow-sm transition hover:bg-slate-50">← 回首頁</Link><button onClick={handleLogout} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 shadow-sm transition hover:bg-slate-50">登出</button></div>}</div>
  <section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-[0_12px_40px_rgba(15,23,42,0.06)] md:p-7"><div className="mb-6"><h2 className="text-xl font-bold text-slate-900">① 設定與上傳</h2><p className="mt-1 text-sm text-slate-500">選擇題庫資訊後，上傳 PDF 開始解析</p></div><div className="grid gap-5 md:grid-cols-3">
   <label className="group rounded-2xl border border-dashed border-slate-300 bg-slate-50/70 p-5 transition hover:border-blue-300 hover:bg-blue-50/30"><span className="font-bold text-slate-800">PDF 檔案</span><input className="mt-4 block w-full cursor-pointer text-sm text-slate-500 file:mr-3 file:rounded-lg file:border-0 file:bg-slate-900 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white hover:file:bg-slate-700" type="file" accept="application/pdf" onChange={handleFileChange}/>{file&&<p className="mt-3 truncate rounded-lg bg-white px-3 py-2 text-sm text-slate-600 shadow-sm">📄 {file.name}</p>}</label>
   <div className="rounded-2xl border border-slate-200 bg-slate-50/50 p-5"><label className="font-bold text-slate-800">國考科目</label><select value={examSubject} onChange={e=>setExamSubject(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 outline-none transition focus:border-blue-400 focus:ring-4 focus:ring-blue-50"><option value="">請選擇科目</option>{EXAM_SUBJECTS.map(s=><option key={s}>{s}</option>)}</select><label className="mt-4 block font-bold text-slate-800">國考年份</label><select value={examYear} onChange={e=>setExamYear(e.target.value?Number(e.target.value):"")} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 outline-none transition focus:border-blue-400 focus:ring-4 focus:ring-blue-50"><option value="">不指定年份</option>{EXAM_YEARS.map(y=><option key={y} value={y}>民國 {y} 年</option>)}</select></div>
   <div className="rounded-2xl border border-slate-200 bg-slate-50/50 p-5"><span className="font-bold text-slate-800">題庫權限</span><div className="mt-3 grid grid-cols-2 gap-3"><button type="button" onClick={()=>setVisibility("private")} className={`rounded-xl border p-4 text-left transition ${visibility==="private"?"border-blue-400 bg-blue-50 shadow-sm":"border-slate-200 bg-white hover:border-slate-300"}`}><b>🔒 私人</b><p className="mt-1 text-xs text-slate-500">只有你可以使用</p></button><button type="button" disabled={!isAdmin} onClick={()=>setVisibility("public")} className={`rounded-xl border p-4 text-left transition ${visibility==="public"?"border-emerald-400 bg-emerald-50 shadow-sm":"border-slate-200 bg-white hover:border-slate-300"} disabled:cursor-not-allowed disabled:opacity-40`}><b>🌐 公開</b><p className="mt-1 text-xs text-slate-500">{isAdmin?"管理員可建立":"僅管理員可建立"}</p></button></div></div>
  </div><button onClick={handleUpload} disabled={loading||!file||!isLoggedIn||!isPro} className="mt-6 rounded-xl bg-slate-900 px-6 py-3 font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-slate-800 disabled:cursor-not-allowed disabled:bg-slate-300">{loading?"解析中...":"開始解析 PDF"}</button>{message&&<div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">{message}</div>}</section>

  <section className="mt-7 rounded-3xl border border-slate-200/80 bg-white p-5 shadow-[0_12px_40px_rgba(15,23,42,0.05)] md:p-7"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold text-slate-900">📁 已匯入的題庫</h2><p className="mt-1 text-sm text-slate-500">管理你已經建立的 PDF 題庫</p></div><button onClick={loadQuestionSets} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-50">重新整理</button></div>{loadingQuestionSets?<p className="mt-5 text-slate-500">載入中...</p>:questionSets.length===0?<div className="mt-5 rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-500">目前還沒有匯入題庫。</div>:<div className="mt-5 space-y-3">{questionSets.map(q=><div key={q.id} className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-slate-50/40 p-4 transition hover:border-slate-300 hover:bg-white md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b className="truncate text-slate-800">{q.name}</b><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${q.visibility==="public"?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}>{q.visibility==="public"?"公開":"私人"}</span>{q.exam_subject&&<span className="rounded-full bg-white px-2.5 py-1 text-xs text-slate-600">{q.exam_subject}</span>}{q.exam_year&&<span className="rounded-full bg-white px-2.5 py-1 text-xs text-slate-600">{q.exam_year-1911} 年</span>}</div><p className="mt-2 truncate text-sm text-slate-500">{q.filename||"PDF 題庫"} · {q.total_questions} 題 · {new Date(q.created_at).toLocaleString("zh-TW")}</p></div><button disabled={deletingQuestionSetId===q.id} onClick={()=>deleteSavedQuestionSet(q)} className="rounded-xl border border-red-200 bg-white px-4 py-2 text-sm font-semibold text-red-600 transition hover:bg-red-50 disabled:opacity-50">{deletingQuestionSetId===q.id?"刪除中...":"刪除題庫"}</button></div>)}</div>}</section>

  {questions.length>0&&<section className="mt-7"><div className="mb-5 rounded-3xl border border-slate-200/80 bg-white p-5 shadow-[0_12px_40px_rgba(15,23,42,0.05)] md:p-7"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="mb-2 inline-flex rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">解析完成 · 待確認</div><h2 className="text-xl font-bold text-slate-900">② 檢查解析結果</h2><p className="mt-1 text-sm text-slate-500">共 {questions.length} 題。請確認文字、選項與圖片。</p></div><button disabled={loading} onClick={confirmImport} className="rounded-xl bg-emerald-600 px-6 py-3 font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50">{loading?"匯入中...":"確認匯入"}</button></div></div><div className="space-y-5">{questions.map((q,i)=><article key={`${q.id}-${i}`} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)] md:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-lg bg-blue-50 px-3 py-1 text-sm font-bold text-blue-700">第 {i+1} 題</span>{q.hasImage&&<span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">🖼 圖片 · 第 {q.pageNumber} 頁</span>}</div><button onClick={()=>deleteQuestion(q.id)} className="rounded-lg px-3 py-1.5 text-sm font-semibold text-red-500 transition hover:bg-red-50">刪除題目</button></div><textarea value={q.question} onChange={e=>updateQuestion(q.id,e.target.value)} rows={4} className="mt-4 w-full resize-y rounded-xl border border-slate-200 bg-slate-50/40 p-4 text-lg font-semibold leading-8 text-slate-800 outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50"/>{q.hasImage&&<ImagePreview file={file} pageNumber={q.pageNumber} questionNumber={q.id}/>}<div className="mt-5 space-y-3">{q.options.map((o,j)=><div key={j} className="flex gap-3"><b className="mt-3 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-sm text-slate-600">{String.fromCharCode(65+j)}</b><textarea value={o} onChange={e=>updateOption(q.id,j,e.target.value)} rows={2} className="w-full resize-y rounded-xl border border-slate-200 bg-white p-3 text-slate-700 outline-none transition focus:border-blue-400 focus:ring-4 focus:ring-blue-50"/></div>)}</div></article>)}</div></section>}
 </div></main>;
}
